version: '3.8'

services:
  mysql:
    image: mysql:8.0.22
    container_name: mysqldb
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: poc1
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
