version: '3.8'
services:
  db:
    container_name: mysqldb-poc1
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
volumes:
  db_data: { }